### ISSUE TITLE
Experiment with unity particles

### ISSUE THREAD

**Issue by beckaa** [beckaa/AnimalStreetCrossing#11]
e.g. make coins shine
or smoke for cars

**Comment by Kr555Dev** [comment]
Hey @beckaa, I am Kartik and I would like to contribute in this issue for your game project. I have 1 year experience in Unity you can check my projects at (https://kartik555dev.itch.io/).  Could you please assign me this issue?

**Comment by beckaa** [comment]
Hi @Kr555Dev  😄 
I assigned the issue to you. We are happy that you want to contribute to this project.
If you have any questions, feel free to ask them.

**Comment by Kr555Dev** [comment]
Thank you @beckaa . I will work on it this weekend. So should I create a separate branch and push my commits into that branch then?

**Comment by beckaa** [comment]
Yes, that would be great. Please make your own Branch 😄
