### ISSUE TITLE
Redesign in-game UI 🎨 

### ISSUE THREAD

**Issue by beckaa** [beckaa/AnimalStreetCrossing#22]
Redesign the in-game menus like the  main menu design 🎨 
- pause screen in Main scene -> restart button??
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/b9d5fc86-c536-48e0-bc27-cb30324c5364)
- win Screen in Main scene
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/a68e349c-126a-423f-b609-80518c9f27bf)
- loose screen in Main scene
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/42dffa35-2407-48a5-b567-227c7b8b2259)
- exit screen in levelMap (go back to main screen, insert button to leave game?)
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/9af39906-7a91-4833-af42-2388b470d07f)

Maybe generally give the opportunity to exit the game in the pause and exit screen ? 
(Instead of close window button an cross in the right corner of the pause screen)

Next Level could be loaded with sceneManager -> get the sceneindex of the current scene -> load the next sceneindex (To do this the levels have to be sorted in the build settings)
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/c86eaeac-8646-46f1-af0f-f1196d630e28)

RENAME: scene main into levelZero ??

create and update the prefabs 
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/0e75ede4-3b56-4f8f-8ee0-836fa6c113e3)
prefabs are blue in hierarchy and assets
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/2409988e-2bbf-4961-bb57-2b64f6650af3)
You can either work in the prefabs directly or work on the objects in the hierarchy.
If working in the hierarchy you can update the prefabs in the inspector window under override
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/947cfe99-1595-42fb-861b-3d9e54c3bdc8)

**Comment by Stephi-x3** [comment]
@beckaa ideas for the icon for 'back to level map'? or an img? an icon with the meaning 'choose something'?
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/1c926e08-82fa-4096-8256-5c4b01e5b955)

**Comment by Stephi-x3** [comment]
or an icon that shows a graph with nodes and edges?

**Comment by Stephi-x3** [comment]
nearly ready. last things to do:

- [ ] opportunity to exit the game -> exit button
- [ ] update/ check button events

**Comment by beckaa** [comment]
> nearly ready. last things to do:
> 
> * [ ]  opportunity to exit the game -> exit button
> * [ ]  update/ check button events

Reuse your exit script from main menu for exit button

**Comment by Stephi-x3** [comment]
decided that exit button should be a lot more different than the close window button. I'm using a door as icon for "exit the game".

**Comment by Stephi-x3** [comment]
- [ ] audio --> click

**Comment by Stephi-x3** [comment]
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/e90287ed-540d-455d-ab9a-94e20ed85d98)
No prefab for this menu?  I could use pauseMenu as foundation. @beckaa  Is there a way to duplicate and then change a prefab?

**Comment by Stephi-x3** [comment]
> * [ ]  audio --> click

added an audio button just like in the main menu. but gameplay shows that it doesn't work every time? pause menu --> back to menu works but the other buttons don't make a sound. didn't find the bug yet.

**Comment by beckaa** [comment]
> ![image](https://user-images.githubusercontent.com/139639918/266830996-e90287ed-540d-455d-ab9a-94e20ed85d98.png) No prefab for this menu? I could use pauseMenu as foundation. @beckaa Is there a way to duplicate and then change a prefab?

prefabs can be created -> just drag and drop it from hierarchy into the prefab folder

**Comment by beckaa** [comment]
> > * [ ]   audio --> click
> 
> added an audio button just like in the main menu. but gameplay shows that it doesn't work every time? pause menu --> back to menu works but the other buttons don't make a sound. didn't find the bug yet.

choosing another level + back to menu works

close button+exit not working?

**Comment by Stephi-x3** [comment]
> > > * [ ]    audio --> click
> > 
> > 
> > added an audio button just like in the main menu. but gameplay shows that it doesn't work every time? pause menu --> back to menu works but the other buttons don't make a sound. didn't find the bug yet.
> 
> choosing another level + back to menu works
> 
> close button+exit not working?
> 
> Sometimes if the audio source "audio button" is set to inactive before a sound can be played the sound will not be played -> placing the sound out of the pause screen (not as child as pause menu) may work ??
> 
> Panel exit game is also not opening because the pause screen is set to inactive -> place the screen not as child of pause screen or change button onClick functions?

Thanks 👍 I check it out 😄

**Comment by beckaa** [comment]
Redesign Highscore Screens:
![Screenshot 2023-09-17 210224](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/08665001-aebf-43b2-b997-0b1a9c0843c9)
![Screenshot 2023-09-17 210312](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/258a9d44-35ca-4a48-b669-dd3c23c742ef)

**Comment by beckaa** [comment]
![Screenshot 2023-09-17 232624](https://github.com/beckaa/AnimalStreetCrossing/assets/44342265/16e741ed-4220-4383-b46e-6ebf904d4024)
On purpose? (seeing car through menu)

**Comment by Stephi-x3** [comment]
> > > * [ ]    audio --> click
> > 
> > 
> > added an audio button just like in the main menu. but gameplay shows that it doesn't work every time? pause menu --> back to menu works but the other buttons don't make a sound. didn't find the bug yet.
> 
> choosing another level + back to menu works
> 
> close button+exit not working?
> 
> Sometimes if the audio source "audio button" is set to inactive before a sound can be played the sound will not be played -> placing the sound out of the pause screen (not as child as pause menu) may work ??
> 
> Panel exit game is also not opening because the pause screen is set to inactive -> place the screen not as child of pause screen or change button onClick functions?


I found something out: When I change scenes (pauseMenu --> levelMap) the audio for the click action seems to be in the
scene I want to go to. I added the audio for the click sound directly in the scene "levelMap". Now when I click on the button "choose another Level" it works... 

The click on "Exit the Game" works if I change the script "GameUI". Seems to be a problem because of the AudioListener...
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/d8a1bffb-8680-4ada-9493-151e3f286673)

I open a new Issue for this and firstly finalize the design here.

**Comment by Stephi-x3** [comment]
Position of List needs to be adjusted after design is ready (it has a fixed, not changeable position at the moment)
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/903d2ebb-1f1e-4d20-8907-6e65764cf099)
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/0879499b-a4f3-4ef8-99aa-9d317918b2e8)

**Comment by beckaa** [comment]
> > > > * [ ]     audio --> click
> > > 
> > > 
> > > added an audio button just like in the main menu. but gameplay shows that it doesn't work every time? pause menu --> back to menu works but the other buttons don't make a sound. didn't find the bug yet.
> > 
> > 
> > choosing another level + back to menu works
> > close button+exit not working?
> > Sometimes if the audio source "audio button" is set to inactive before a sound can be played the sound will not be played -> placing the sound out of the pause screen (not as child as pause menu) may work ??
> > Panel exit game is also not opening because the pause screen is set to inactive -> place the screen not as child of pause screen or change button onClick functions?
> 
> I found something out: When I change scenes (pauseMenu --> levelMap) the audio for the click action seems to be in the scene I want to go to. I added the audio for the click sound directly in the scene "levelMap". Now when I click on the button "choose another Level" it works...
> 
> The click on "Exit the Game" works if I change the script "GameUI". Seems to be a problem because of the AudioListener... ![image](https://user-images.githubusercontent.com/139639918/278861371-d8a1bffb-8680-4ada-9493-151e3f286673.png)
> 
> I open a new Issue for this and firstly finalize the design here.

In the level map scene a button has a checked "play on awake" box -> that's the reason why a sound is played in the beginning of the scene.

**Comment by Stephi-x3** [comment]
@beckaa proposal: Version 1 or 2?

- Version 1: Popup as overlay/ Gamer can see the highscore list in the background. --> Popup will get another design if you prefer this version
- Version 2: Highscore list not shown. Gamer types in his name --> then highscore list is shown

### Version 1
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/752ed251-c17a-41fe-aa97-b8b9f1aa1119)

### Version 2
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/2921cf53-9a95-465b-bacb-90864335366a)
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/4038332d-4ae8-415e-8f87-8430767eaf7d)

**Comment by beckaa** [comment]
> @beckaa proposal: Version 1 or 2?
> 
>     * Version 1: Popup as overlay/ Gamer can see the highscore list in the background. --> Popup will get another design if you prefer this version
> 
>     * Version 2: Highscore list not shown. Gamer types in his name --> then highscore list is shown
> 
> 
> ### Version 1
> 
> ![image](https://user-images.githubusercontent.com/139639918/279050380-752ed251-c17a-41fe-aa97-b8b9f1aa1119.png)
> ### Version 2
> 
> ![image](https://user-images.githubusercontent.com/139639918/279047918-2921cf53-9a95-465b-bacb-90864335366a.png) ![image](https://user-images.githubusercontent.com/139639918/279050176-4038332d-4ae8-415e-8f87-8430767eaf7d.png)

I think I would prefer version 2
(User might close the highscorelist before typing his/her name, if the popup is an overlay)
