### ISSUE TITLE
Find the Problem: Button Click Sound

### ISSUE THREAD

**Issue by Stephi-x3** [beckaa/AnimalStreetCrossing#39]
### Aim of this Issue: 
When clicking on a button the following sound should be played:
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/ba36b310-639d-42b6-878d-a5661321b4be)
### The problem:
It fully works in the Main Menu but not in the Prefabs (PauseMenu, LooseMenu, ...) where the button click leads to a scene change. The problem could be related with the AudioListener. Also: The problem with the button "choose another level" was fixed by adding the sound to the target scene (levelMap).
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/b8d04a48-b67d-4e4f-936e-5641025be876)
![image](https://github.com/beckaa/AnimalStreetCrossing/assets/139639918/0c512496-ed8b-43b4-88dc-71e62f035337)

**Comment by beckaa** [comment]
added new way to pause and unpause the in-game music (pause screen)
-> pushed it to design branch 
->check it out on your branch

**Comment by Stephi-x3** [comment]
- [ ] sounds in the win menu

- [ ] closing highscorelist (close button)

- [ ] sound for "Save" playername button
